# Generated by Django 4.0.3 on 2022-10-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(max_length=1000)),
                ('resumen', models.TextField(max_length=100)),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_nombre', models.CharField(max_length=200)),
                ('casa_descripcion', models.TextField(max_length=500)),
                ('casa_direccion', models.CharField(max_length=200)),
                ('casa_habitantes', models.IntegerField()),
                ('casa_cuartos', models.IntegerField()),
                ('casa_amueblada', models.BooleanField()),
                ('casa_contacto', models.IntegerField()),
                ('home_photo', models.ImageField(upload_to='files/covers')),
                ('casa_aprobada', models.BooleanField(default=False)),
                ('casa_rentada', models.BooleanField(default=False)),
                ('casa_responsable', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casaspropias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
